# Generated by Django 5.2.5 on 2025-08-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(max_length=512),
        ),
    ]
