# Generated by Django 5.2.5 on 2025-08-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_alter_task_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
